use Mix.Config

# Configure your database
config :eworks, Eworks.Repo,
  username: "postgres",
  password: "okari5678",
  database: "eworks_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

  # configure guardian
config :eworks, EworksWeb.Authentication.Guardian,
  issuer: "eworks",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# configure the aws
config :ex_aws,
  # use the default phoenix jason_library
  json_codec: Jason,
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  region: System.get_env("AWS_REGION")

# configuration for aws s3 storage
# config :ex_aws,
#   # use the default phoenix jason_library
#   json_codec: Jason,
#   access_key_id: System.get_env("SECRET_ACCESS_KEY"),
#   secret_access_key: System.get_env("ACCESS_KEY_ID"),
#   region: System.get_env("AWS_REGION")

config :waffle,
  storage: Waffle.Storage.S3,
  # set the virtual to true
  virtual_host: true,
  # bucket name
  bucket: System.get_env("AWS_S3_BUCKET_NAME"),
  # the asset host
  asset_host: System.get_env("AWS_S3_ASSET_HOST"),
  # the version timroute
  version_timeout: 100_000

# configuration for bamboo
config :eworks, Eworks.Utils.Mailer,
  adapter: Bamboo.LocalAdapter

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :eworks, EworksWeb.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  url: [host: "localhost"],
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
